export const UPDATE_CONNECTION_ACCOUNT_NAME = "UPDATE_CONNECTION_ACCOUNT_NAME";
export const UPDATE_CONNECTION_CONTAINER_NAME = "UPDATE_CONNECTION_CONTAINER_NAME";
export const UPDATE_CONNECTION_SAS_TOKEN = "UPDATE_CONNECTION_SAS_TOKEN";
export const UPDATE_CONNECTION_RECORDING = "UPDATE_CONNECTION_RECORDING";
export const UPDATE_CONNECTION_META_FILE_HANDLE = "UPDATE_CONNECTION_META_FILE_HANDLE";
export const UPDATE_CONNECTION_DATA_FILE_HANDLE = "UPDATE_CONNECTION_DATA_FILE_HANDLE";